### ISSUE TITLE
在centos上无法运行 报错信息如下

### ISSUE THREAD

**Issue by StrangeYear** [Coolpy7/coolpy7_benchmark#1]
`2019/04/25 18:17:19 0
2019/04/25 18:17:19 conn no ip cat use
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7241c9]

goroutine 1 [running]:
main.main()
	D:/GolandProjects/coolpy7_benchmark/test_bench_sub/cp7_bench_sub.go:54 +0x4b9`

这个好像是找不到windows系统的路径？

**Comment by jacoblai** [comment]
这个错误是原因是我的测试连接代码为了用更多的网卡进行更大并发的测试，所以设计了一个loop取当前网络环境的虚拟IP，如果使用一个手机热点或并没有配置虚拟ip的网络环境可能会出现这个错误，请参阅https://coolpy7.gitbook.io/coolpy7book/kai-shi-shi-yong/dan-ji-qian-wan-ji-lian-jie-ce-shi-shuo-ming中的增加虚拟ip部分的说明。

**Comment by jacoblai** [comment]
说明白点 就是你需要一个正常的路由器来做这个测试，你可以考滤拿一个全新的路由器来做这个测试。

**Comment by DongGuangHui0707** [comment]
@jacoblai 在CentsOS 的VM上同样的问题，也是需要增加虚拟IP，VM
的IP就是虚拟的IP了，这个怎么解呢？多谢！

**Comment by jacoblai** [comment]
没用过vm做这个事情，请到网上查一下资料。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DongGuangHui0707 <notifications@github.com&gt;
发送时间: 2020年12月30日 10:38
收件人: Coolpy7/coolpy7_benchmark <coolpy7_benchmark@noreply.github.com&gt;
抄送: Li Donghai <5241871@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[Coolpy7/coolpy7_benchmark] 在centos上无法运行 报错信息如下 (#1)





 
@jacoblai 在CentsOS 的VM上同样的问题，也是需要增加虚拟IP，VM
 的IP就是虚拟的IP了，这个怎么解呢？多谢！
