### ISSUE TITLE
为什么测试连接数增长很慢？

### ISSUE THREAD

**Issue by linxingyang** [Coolpy7/coolpy7_benchmark#4]
您好。

我按照您的这篇博客 [单机千万级MQTT连接服务器测试报告](https://www.cnblogs.com/jacle169/p/10551062.html) 中使用的测试工具，就是当前这个测试工具进行测试。

我看您的连接数涨得非常快，基本1秒1000多：
![图](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-LPz4APWKTuf0FRQG1lh%2F-LSOUG53G_cvouKuDDLH%2F-LSOTmIJCGeyE-8_mamF%2FTIM%E5%9B%BE%E7%89%8720181106135503.png?alt=media&token=7ad5ff70-80c4-4c82-8265-95ebc202b170)

而我这边测试订阅，连接数涨的很慢，几次测试都是，从0涨到1W需要1分钟左右，从1W涨到2W需要更长的时间
- 1、订阅的主题是直接复制的，就改了一下其中的url部分。
```
./go_build_cp7_bench_sub_go_linux -workers=4000000 -cid=tqy -topic=null -qos=0 -url=tcp://192.168.200.238:1883 -keepalive=60000s -clear=true
```
- 2、服务端、客户端相关参数也与博客中的几乎一致，部分数值可能不一样，不过那些数值不会影响到连接的速度。
- 3、两台服务器之间通过一个独立的千兆交换机（交换机上就接着我的笔记本，服务器A，服务器B）通讯。
- 4、使用jmeter进行测试过，那个连接增长的速度是正常的，很快能够涨到1W，接着2W。

您知道有可能是什么原因吗？

linxy.

**Comment by jacoblai** [comment]
请问你用的是最新版本吗？最新版本增加了防self-ddos连接攻击功能，所以连接会补限速。你如果确定要测试的话我需要把参数开放出来。

**Comment by jacoblai** [comment]
https://github.com/Coolpy7/coolpy7_benchmark/blob/master/bin/go_build_Coolpy7_go_amd64_linux
已上传取消self-ddos限制的版本。

**Comment by linxingyang** [comment]
对，我是下载的最新的版本。
您刚刚上传的go_build_Coolpy7_go_amd64_linux是MQTT服务端吧？我测试用的MQTT服务端是mosquitto。

最近访问国外github时常断，回复有点慢，不好意思。

linxy.

**Comment by jacoblai** [comment]
明白了，你用的不是cp7服务器端，所以慢是你在测试的服务器端造成的，说明你在测试的服务器端就是这么慢的连接性能。因为本项目测试客户端很久没有更新过，基本上还是我写测评报告时的代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 林兴洋(XingYangLin) ***@***.***&gt;
发送时间: 2021年3月11日 22:31
收件人: Coolpy7/coolpy7_benchmark ***@***.***&gt;
抄送: Li Donghai ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[Coolpy7/coolpy7_benchmark] 为什么测试连接数增长很慢？ (#4)

**Comment by linxingyang** [comment]
可是相同的客户端服务器，我使用jmeter进行连接操作的时候速度是正常的。
> 4、使用jmeter进行测试过，那个连接增长的速度是正常的，很快能够涨到1W，接着2W。
难道是和连接本身机制有关系吗？jmeter是多线程去连接，cp7客户端不是？

linxy.

**Comment by jacoblai** [comment]
这点我也无法回答，可能你说的是对的，因为我没用过你说的软件，所以我也不敢随便评论。此项目没有做任何特别的处理，可能和go协程有关。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 林兴洋(XingYangLin) ***@***.***&gt;
发送时间: 2021年3月11日 22:48
收件人: Coolpy7/coolpy7_benchmark ***@***.***&gt;
抄送: Li Donghai ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[Coolpy7/coolpy7_benchmark] 为什么测试连接数增长很慢？ (#4)
